// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ExchangeAdvisor.ML.Model
{
    public class ModelInput
    {
        [ColumnName("Year"), LoadColumn(0)]
        public float Year { get; set; }


        [ColumnName("Month"), LoadColumn(1)]
        public float Month { get; set; }


        [ColumnName("Day"), LoadColumn(2)]
        public float Day { get; set; }


        [ColumnName("Absolute day number"), LoadColumn(3)]
        public float AbsoluteDayNumber { get; set; }


        [ColumnName("Day of week"), LoadColumn(4)]
        public string DayOfWeek { get; set; }


        [ColumnName("Day of year"), LoadColumn(5)]
        public float DayOfTear { get; set; }


        [ColumnName("Rate"), LoadColumn(6)]
        public float Rate { get; set; }


        [ColumnName("Base currency"), LoadColumn(7)]
        public string BaseCurrency { get; set; }


        [ColumnName("Comparing currency"), LoadColumn(8)]
        public string ComparingCurrency { get; set; }
    }
}
